
spring:
  application:
    name: msvc-acreditaciones

  datasource:
    url: jdbc:mysql://localhost:3306/desafio_tecnico?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

springdoc:
  swagger-ui:
    path: ${spring.application.name}/swagger-ui.html